name: Build x86 Curl with OpenSSL 3.x

on:
  push:
    branches: [ test ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Build Script
        working-directory: ./curl
        run: |
          chmod +x curl.sh
          sudo ./curl.sh

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: curl-x86-openssl3
          path: |
            curl_i686_openssl3.exe
            libcrypto-3.dll
            libssl-3.dll
            release.md
